// Tests the distribution generated by Java's Math.random() function.
public  class  TestRandom {
	public static void main(String[]  args) {
	    int iteration = Integer.parseInt(args[0]);
		int more_than_half = 0;
		int equal_or_less_than_half = 0;
	for(int i = 0; i < iteration;i++) {
		if (Math.random()>0.5) {
			more_than_half= more_than_half+1;
		}
		else
		{
			equal_or_less_than_half= equal_or_less_than_half+1;
		}
	}
	if (equal_or_less_than_half > 0 && more_than_half != 0 )
	{
		System.out.println("> 0.5: " + more_than_half + " times");
		System.out.println("<= 0.5: " + equal_or_less_than_half + " times");
		double ratio = (double)more_than_half / (double)equal_or_less_than_half;
		System.out.println("Ratio: "+(double)ratio); 
	}
	else
	{
		System.out.println("> 0.5: " + more_than_half + " times");
		System.out.println("<= 0.5: " + equal_or_less_than_half + " times");	
	}
	}
}
